// Text prompts for the Imposter game with theme packs
// Each round will randomly select 3-5 prompts from the selected theme pack

export interface ThemePack {
  id: string;
  name: string;
  description: string;
  icon: string;
  prompts: string[];
}

export const themePacks: ThemePack[] = [
  {
    id: 'personal',
    name: 'Personal Life',
    description: 'Questions about daily life and personal preferences',
    icon: '🏠',
    prompts: [
      "What's your favorite breakfast food?",
      "What's the last app you opened on your phone?",
      "What household chore do you hate the most?",
      "What's your go-to comfort food?",
      "What's your favorite type of weather?",
      "What's the last movie you watched?",
      "What's your favorite season?",
      "What's your dream vacation destination?",
      "What's your favorite type of music?",
      "What's your biggest pet peeve?",
      "What did you have for lunch today?",
      "What time did you wake up this morning?",
      "What's your morning routine?",
      "What's the last thing you bought?",
      "What's your favorite way to relax?",
      "What's your least favorite day of the week?",
      "What's your favorite room in your house?",
      "What's your typical weekend activity?",
      "What's your favorite way to exercise?",
      "What's your bedtime routine?",
      "What's your favorite type of coffee?",
      "What's your go-to midnight snack?",
      "What's your least favorite household smell?",
      "What's your favorite type of pillow?",
      "What's your preferred way to wake up?",
      "What's your favorite type of blanket?",
      "What's your go-to lazy day activity?",
      "What's your favorite type of pajamas?",
      "What's your preferred way to cool down?",
      "What's your favorite type of heating?",
      "What's your go-to rainy day activity?",
      "What's your favorite type of lighting?",
      "What's your preferred way to stay warm?",
      "What's your favorite type of window view?",
      "What's your go-to cleaning motivation?",
      "What's your favorite type of home decoration?",
      "What's your preferred way to organize?",
      "What's your favorite type of storage?",
      "What's your go-to home improvement project?"
    ]
  },
  {
    id: 'technology',
    name: 'Technology & Media',
    description: 'Questions about apps, games, and digital life',
    icon: '💻',
    prompts: [
      "What's your favorite social media platform?",
      "What's the last YouTube video you watched?",
      "What's your favorite streaming service?",
      "What's your most used app?",
      "What's your favorite video game?",
      "What's your preferred way to listen to music?",
      "What's your favorite type of content to watch?",
      "What's your go-to news source?",
      "What's your favorite website?",
      "What's your preferred way to communicate?",
      "What's your favorite programming language?",
      "What's your go-to search engine?",
      "What's your favorite type of podcast?",
      "What's your preferred way to take notes?",
      "What's your favorite type of online content?",
      "What's your go-to productivity app?",
      "What's your favorite type of social media post?",
      "What's your preferred way to watch movies?",
      "What's your favorite type of online game?",
      "What's your go-to messaging app?",
      "What's your favorite type of keyboard?",
      "What's your preferred way to backup data?",
      "What's your favorite type of cloud storage?",
      "What's your go-to password manager?",
      "What's your favorite type of browser?",
      "What's your preferred way to sync devices?",
      "What's your favorite type of smart home device?",
      "What's your go-to photo editing app?",
      "What's your favorite type of email client?",
      "What's your preferred way to manage files?",
      "What's your favorite type of calendar app?",
      "What's your go-to note-taking method?",
      "What's your favorite type of browser extension?",
      "What's your preferred way to block distractions?",
      "What's your favorite type of automation?",
      "What's your go-to screen recording tool?",
      "What's your favorite type of virtual meeting?",
      "What's your preferred way to manage subscriptions?",
      "What's your favorite type of digital wallet?"
    ]
  },
  {
    id: 'food',
    name: 'Food & Drink',
    description: 'Questions about culinary preferences and dining',
    icon: '🍕',
    prompts: [
      "What's your favorite type of cuisine?",
      "What's your go-to coffee order?",
      "What's your favorite snack?",
      "What's your least favorite food?",
      "What's your favorite type of dessert?",
      "What's your preferred way to cook?",
      "What's your favorite restaurant chain?",
      "What's your go-to drink?",
      "What's your favorite type of bread?",
      "What's your preferred way to eat pizza?",
      "What's your favorite type of pasta?",
      "What's your go-to breakfast?",
      "What's your favorite type of sandwich?",
      "What's your preferred way to eat ice cream?",
      "What's your favorite type of soup?",
      "What's your go-to late night snack?",
      "What's your favorite type of salad?",
      "What's your preferred way to eat tacos?",
      "What's your favorite type of smoothie?",
      "What's your go-to comfort drink?",
      "What's your favorite type of spice?",
      "What's your preferred way to season food?",
      "What's your favorite type of cooking oil?",
      "What's your go-to kitchen gadget?",
      "What's your favorite type of herb?",
      "What's your preferred way to store leftovers?",
      "What's your favorite type of condiment?",
      "What's your go-to food prep method?",
      "What's your favorite type of cooking method?",
      "What's your preferred way to eat vegetables?",
      "What's your favorite type of protein?",
      "What's your go-to healthy snack?",
      "What's your favorite type of grain?",
      "What's your preferred way to eat fruit?",
      "What's your favorite type of dairy product?",
      "What's your go-to food preservation method?",
      "What's your favorite type of cooking show?",
      "What's your preferred way to try new foods?",
      "What's your favorite type of food memory?"
    ]
  },
  {
    id: 'hobbies',
    name: 'Hobbies & Interests',
    description: 'Questions about activities and personal interests',
    icon: '🎨',
    prompts: [
      "What's your favorite hobby?",
      "What's your favorite type of book?",
      "What's your preferred way to spend free time?",
      "What's your favorite type of art?",
      "What's your go-to stress relief activity?",
      "What's your favorite type of puzzle?",
      "What's your preferred way to learn new things?",
      "What's your favorite type of craft?",
      "What's your go-to party game?",
      "What's your favorite type of collection?",
      "What's your favorite type of sport to watch?",
      "What's your go-to creative outlet?",
      "What's your favorite type of board game?",
      "What's your preferred way to garden?",
      "What's your favorite type of photography?",
      "What's your go-to workout routine?",
      "What's your favorite type of dance?",
      "What's your preferred way to meditate?",
      "What's your favorite type of instrument?",
      "What's your go-to relaxation technique?",
      "What's your favorite type of puzzle game?",
      "What's your preferred way to learn languages?",
      "What's your favorite type of card game?",
      "What's your go-to creative writing prompt?",
      "What's your favorite type of outdoor activity?",
      "What's your preferred way to collect things?",
      "What's your favorite type of DIY project?",
      "What's your go-to mental exercise?",
      "What's your favorite type of strategy game?",
      "What's your preferred way to practice mindfulness?",
      "What's your favorite type of word game?",
      "What's your go-to artistic medium?",
      "What's your favorite type of trivia?",
      "What's your preferred way to build things?",
      "What's your favorite type of role-playing?",
      "What's your go-to competitive activity?",
      "What's your favorite type of storytelling?",
      "What's your preferred way to explore creativity?",
      "What's your favorite type of skill to develop?"
    ]
  },
  {
    id: 'travel',
    name: 'Travel & Adventure',
    description: 'Questions about places and experiences',
    icon: '✈️',
    prompts: [
      "What's your dream vacation destination?",
      "What's your favorite type of accommodation?",
      "What's your go-to travel snack?",
      "What's your least favorite part of traveling?",
      "What's your favorite type of transportation?",
      "What's your preferred way to plan trips?",
      "What's your favorite type of souvenir?",
      "What's your go-to travel app?",
      "What's your favorite type of landscape?",
      "What's your preferred way to document trips?",
      "What's your favorite type of adventure?",
      "What's your go-to travel outfit?",
      "What's your favorite type of local food to try?",
      "What's your preferred way to navigate?",
      "What's your favorite type of travel photo?",
      "What's your go-to travel playlist?",
      "What's your favorite type of cultural experience?",
      "What's your preferred way to pack?",
      "What's your favorite type of travel companion?",
      "What's your go-to travel memory?",
      "What's your favorite type of travel accommodation?",
      "What's your preferred way to book flights?",
      "What's your favorite type of travel insurance?",
      "What's your go-to travel planning app?",
      "What's your favorite type of travel guide?",
      "What's your preferred way to handle jet lag?",
      "What's your favorite type of travel currency?",
      "What's your go-to travel safety tip?",
      "What's your favorite type of travel souvenir?",
      "What's your preferred way to learn local customs?",
      "What's your favorite type of travel challenge?",
      "What's your go-to travel packing hack?",
      "What's your favorite type of travel experience?",
      "What's your preferred way to document adventures?",
      "What's your favorite type of travel companion?",
      "What's your go-to travel emergency plan?",
      "What's your favorite type of travel reward?",
      "What's your preferred way to stay connected?",
      "What's your favorite type of travel discovery?"
    ]
  },
  {
    id: 'work',
    name: 'Work & Career',
    description: 'Questions about professional life and work preferences',
    icon: '💼',
    prompts: [
      "What's your favorite part of your job?",
      "What's your go-to productivity method?",
      "What's your least favorite work task?",
      "What's your preferred way to take breaks?",
      "What's your favorite type of meeting?",
      "What's your go-to work snack?",
      "What's your favorite type of project?",
      "What's your preferred way to organize tasks?",
      "What's your favorite type of work environment?",
      "What's your go-to stress management technique?",
      "What's your favorite type of team activity?",
      "What's your preferred way to learn new skills?",
      "What's your favorite type of work communication?",
      "What's your go-to motivation technique?",
      "What's your favorite type of work challenge?",
      "What's your preferred way to celebrate success?",
      "What's your favorite type of work tool?",
      "What's your go-to problem-solving approach?",
      "What's your favorite type of work relationship?",
      "What's your preferred way to end the workday?",
      "What's your go-to professional development method?",
      "What's your favorite type of work collaboration?",
      "What's your preferred way to give feedback?",
      "What's your favorite type of work recognition?",
      "What's your go-to work-life balance strategy?",
      "What's your favorite type of work environment?",
      "What's your preferred way to manage deadlines?",
      "What's your favorite type of work innovation?",
      "What's your go-to work motivation technique?",
      "What's your favorite type of work relationship?",
      "What's your preferred way to handle work stress?",
      "What's your favorite type of work learning?",
      "What's your go-to work communication style?",
      "What's your favorite type of work achievement?",
      "What's your preferred way to network professionally?",
      "What's your favorite type of work mentorship?",
      "What's your go-to work problem-solving approach?",
      "What's your favorite type of work celebration?"
    ]
  },
  {
    id: 'random',
    name: 'Random Mix',
    description: 'A random selection from all theme packs',
    icon: '🎲',
    prompts: [] // Will be populated dynamically
  },
  {
    id: 'pop_culture',
    name: 'Pop Culture',
    description: 'Questions about movies, TV, celebrities, and trends',
    icon: '🎬',
    prompts: [
      "What's your favorite movie genre?",
      "What's the last TV show you binged?",
      "What's your favorite streaming platform?",
      "What's your go-to comfort show?",
      "What's your favorite type of music video?",
      "What's your preferred way to discover new music?",
      "What's your favorite type of social media content?",
      "What's your go-to podcast genre?",
      "What's your favorite type of YouTube video?",
      "What's your preferred way to watch sports?",
      "What's your favorite type of celebrity interview?",
      "What's your go-to entertainment app?",
      "What's your favorite type of movie ending?",
      "What's your preferred way to follow news?",
      "What's your favorite type of viral trend?",
      "What's your go-to music discovery method?",
      "What's your favorite type of reality show?",
      "What's your preferred way to watch concerts?",
      "What's your favorite type of comedy?",
      "What's your go-to entertainment recommendation?",
      "What's your favorite type of movie trailer?",
      "What's your preferred way to discover new shows?",
      "What's your favorite type of celebrity news?",
      "What's your go-to entertainment review source?",
      "What's your favorite type of music festival?",
      "What's your preferred way to follow celebrities?",
      "What's your favorite type of entertainment award?",
      "What's your go-to entertainment discussion topic?",
      "What's your favorite type of viral video?",
      "What's your preferred way to share entertainment?",
      "What's your favorite type of entertainment controversy?",
      "What's your go-to entertainment prediction?",
      "What's your favorite type of entertainment comeback?",
      "What's your preferred way to consume entertainment?",
      "What's your favorite type of entertainment collaboration?",
      "What's your go-to entertainment debate topic?",
      "What's your favorite type of entertainment nostalgia?",
      "What's your preferred way to support artists?",
      "What's your favorite type of entertainment surprise?"
    ]
  },
  {
    id: 'science',
    name: 'Science & Nature',
    description: 'Questions about scientific topics and natural phenomena',
    icon: '🔬',
    prompts: [
      "What's your favorite scientific field?",
      "What's the most fascinating natural phenomenon?",
      "What's your preferred way to learn about science?",
      "What's your favorite type of experiment?",
      "What's your go-to science documentary?",
      "What's your favorite type of animal?",
      "What's your preferred way to observe nature?",
      "What's your favorite type of weather?",
      "What's your go-to science app?",
      "What's your favorite type of space content?",
      "What's your preferred way to study biology?",
      "What's your favorite type of chemistry?",
      "What's your go-to physics concept?",
      "What's your favorite type of geology?",
      "What's your preferred way to explore astronomy?",
      "What's your favorite type of environmental topic?",
      "What's your go-to science podcast?",
      "What's your favorite type of research?",
      "What's your preferred way to understand evolution?",
      "What's your favorite type of scientific discovery?",
      "What's your preferred way to learn about space?",
      "What's your favorite type of scientific experiment?",
      "What's your go-to science news source?",
      "What's your favorite type of natural phenomenon?",
      "What's your preferred way to understand climate?",
      "What's your favorite type of scientific theory?",
      "What's your go-to science learning method?",
      "What's your favorite type of scientific breakthrough?",
      "What's your preferred way to explore nature?",
      "What's your favorite type of scientific mystery?",
      "What's your go-to science documentary genre?",
      "What's your favorite type of scientific application?",
      "What's your preferred way to study evolution?",
      "What's your favorite type of scientific observation?",
      "What's your go-to science communication style?",
      "What's your favorite type of scientific innovation?",
      "What's your preferred way to understand physics?",
      "What's your favorite type of scientific collaboration?",
      "What's your go-to science inspiration source?"
    ]
  },
  {
    id: 'relationships',
    name: 'Relationships & Social',
    description: 'Questions about friendships, family, and social connections',
    icon: '👥',
    prompts: [
      "What's your favorite type of friendship?",
      "What's your go-to way to make new friends?",
      "What's your favorite type of family tradition?",
      "What's your preferred way to resolve conflicts?",
      "What's your favorite type of social gathering?",
      "What's your go-to way to show appreciation?",
      "What's your favorite type of romantic gesture?",
      "What's your preferred way to give advice?",
      "What's your favorite type of group activity?",
      "What's your go-to way to celebrate others?",
      "What's your favorite type of social media interaction?",
      "What's your preferred way to maintain long-distance relationships?",
      "What's your favorite type of community event?",
      "What's your go-to way to support friends?",
      "What's your favorite type of social challenge?",
      "What's your preferred way to meet new people?",
      "What's your favorite type of relationship milestone?",
      "What's your go-to way to handle social anxiety?",
      "What's your favorite type of social learning?",
      "What's your preferred way to build trust?"
    ]
  },
  {
    id: 'health',
    name: 'Health & Wellness',
    description: 'Questions about physical and mental health',
    icon: '🏥',
    prompts: [
      "What's your favorite type of exercise?",
      "What's your go-to stress relief method?",
      "What's your favorite type of healthy snack?",
      "What's your preferred way to track health?",
      "What's your favorite type of wellness routine?",
      "What's your go-to way to improve sleep?",
      "What's your favorite type of mental health practice?",
      "What's your preferred way to stay hydrated?",
      "What's your favorite type of recovery activity?",
      "What's your go-to way to boost energy?",
      "What's your favorite type of health goal?",
      "What's your preferred way to manage pain?",
      "What's your favorite type of wellness app?",
      "What's your go-to way to improve mood?",
      "What's your favorite type of health checkup?",
      "What's your preferred way to build habits?",
      "What's your favorite type of wellness challenge?",
      "What's your go-to way to prevent illness?",
      "What's your favorite type of health education?",
      "What's your preferred way to maintain wellness?"
    ]
  },
  {
    id: 'education',
    name: 'Learning & Education',
    description: 'Questions about learning, studying, and knowledge',
    icon: '📚',
    prompts: [
      "What's your favorite type of learning method?",
      "What's your go-to way to remember information?",
      "What's your favorite type of educational content?",
      "What's your preferred way to take notes?",
      "What's your favorite type of study environment?",
      "What's your go-to way to stay motivated while learning?",
      "What's your favorite type of educational technology?",
      "What's your preferred way to test knowledge?",
      "What's your favorite type of learning challenge?",
      "What's your go-to way to understand complex topics?",
      "What's your favorite type of educational resource?",
      "What's your preferred way to share knowledge?",
      "What's your favorite type of learning community?",
      "What's your go-to way to overcome learning obstacles?",
      "What's your favorite type of educational experience?",
      "What's your preferred way to track learning progress?",
      "What's your favorite type of learning inspiration?",
      "What's your go-to way to apply new knowledge?",
      "What's your favorite type of educational discussion?",
      "What's your preferred way to continue learning?"
    ]
  }
];

// Legacy support - keep the old array for backward compatibility
export const textPrompts = themePacks.flatMap(pack => pack.prompts);

// Function to get random prompts for a round from a specific theme pack
export function getRandomPromptsFromTheme(themeId: string, count: number = 3): string[] {
  let pack = themePacks.find(p => p.id === themeId);
  
  // If theme is 'random' or not found, use all prompts
  if (!pack || themeId === 'random') {
    const allPrompts = themePacks.flatMap(p => p.prompts);
    const shuffled = [...allPrompts].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, Math.min(count, allPrompts.length));
  }
  
  const shuffled = [...pack.prompts].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, Math.min(count, pack.prompts.length));
}

// Function to get random prompts for a round (legacy support)
export function getRandomPrompts(count: number = 3): string[] {
  return getRandomPromptsFromTheme('random', count);
}

// Function to get all available theme packs
export function getThemePacks(): ThemePack[] {
  return themePacks;
}

// Function to get a specific theme pack by ID
export function getThemePack(themeId: string): ThemePack | undefined {
  return themePacks.find(pack => pack.id === themeId);
}
